config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-carmine-tarantula.sh
        container: qc.acc_blurry-buff-wolfhound
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-wheat-greyhound.sh
        container: qc.doc_woolly-platinum-turtle
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cream-boar.sh
        container: qc.doc_muzzy-green-rat
      bitbucket.org/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chestnut-sparrow.sh
        container: qc.doc_pasty-chestnut-spaniel
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-persimmon-flounder.sh
        container: qc.lic_snappy-indigo-rattlesnake
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lavender-capuchin.sh
        container: qc.met_jumpy-tomato-argentino
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-azure-dhole.sh
        container: qc.sty_leaky-taupe-pinscher
      bitbucket.org/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-champagne-flounder.sh
        container: qc.sty_sleazy-zucchini-maltese
      bitbucket.org/cessda/cessda.cdc.searchkit stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lavender-penguin.sh
        container: qc.sty_wiggy-ultramarine-stingray
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-teal-drever.sh
        container: qc.ver_muzzy-brass-crocodile
timeout: 1800
